import type { GetServerSideProps, NextPage } from "next";
import { getServerAuthSession } from "@server/auth";
import { Dashboard } from "@components/shared/dashboard/Dashboard";
import Head from "next/head";
import { api } from "@utils/api";
import { EditGroupForm } from "@components/group/EditGroupForm";
import Loading from "@components/shared/Loading";

const CreateGroupDashboard: NextPage<{ groupId: string }> = ({
  groupId,
}) => {
  const { data: groupData, isLoading: groupLoading } =
    api.group.getGroupById.useQuery({
      id: groupId,
    });
  if (groupLoading) return <Loading />;
  if (!groupData) return <h1 className="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">Group not found</h1>
  return (
    <>
      <Head>
        <title>T3-Dataportal - Create Org</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard current="groups">
        <div className="max-w-xl px-4 sm:px-6 lg:px-8">
          <h1 className="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">
            Edit "{groupData.title}"
          </h1>
          <div className="sm:flex sm:items-center">
            <div className="sm:flex-auto">
              <p className="mt-2 text-sm text-gray-700">
                Groups reflect the structure of your portal, every
                dataset must be assigned to an organization
              </p>
            </div>
          </div>
          {groupData && (
            <div className="mt-8 flow-root">
              <EditGroupForm group={groupData} />
            </div>
          )}
        </div>
      </Dashboard>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
      groupId:
        context.params && typeof context.params.groupId === "string"
          ? context.params.groupId
          : "",
    },
  };
};

export default CreateGroupDashboard;
